Improve error handling
Rapptz/discord-ext-menus pull request #31
Opened 2021-02-22 01:10 UTC by mikeshardmind

- Stops printing errors directly to stderr
- Provides an overridable interface for handling errors which occur
  during update, useful if wanting to terminate menus which error on
  update

2021-02-22 08:05 UTC, Rapptz requested changes
Just a minor name change.

2021-02-22 08:05 UTC, Rapptz commented on discord/ext/menus/__init__.py
> +    async def menu_update_error_handler(self, exc: Exception):
```suggestion
    async def on_menu_button_error(self, exc):
```

(there's no type hinting in the library at the moment)

2021-02-22 09:35 UTC, NCPlayz requested changes

2021-02-22 09:35 UTC, NCPlayz commented on discord/ext/menus/__init__.py
> +        The default behavior is to log the exception.
```suggestion
        The default behaviour is to log the exception.
```

2021-02-22 09:35 UTC, NCPlayz commented on discord/ext/menus/__init__.py
> +            The exception which was raised during a menu update
```suggestion
            The exception which was raised during a menu update.
```

2021-02-23 02:20 UTC, Rapptz approved these changes

2021-02-23 02:21 UTC, merged